### PR TITLE
BUG: preserve file permissions for sdist

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-82

Note that the bug report is only about the sdist. The wheel generation uses `shutil.copy2`, which should do the right thing already.

### CODE REVIEW

**Comment by rgommers** [comment]
Ah fun to test - git does not preserve permissions aside from the executable bit. The checkout depends on `umask` (see https://stackoverflow.com/questions/22239508/git-pull-is-setting-664-instead-of-644-permissions), so we see `644` on Linux/macOS and `666` on Windows in CI.

For installing a wheel, only the executable bit matters, `pip` does not preserve the rest: https://github.com/pypa/pip/blob/d0051d3266ba11e7410a43a040dfd409af88a1db/src/pip/_internal/utils/unpacking.py#L105-L110

So the bug fix is fine here, but for a robust test it looks like we should only test the executable bit.

**Comment by rgommers** [comment]
@FFY00 would you then prefer this to be a separate test, rather than included in `test_contents_subdirs`?

**Comment by FFY00** [comment]
Yep, I would, but this is acceptable too.

**Comment by h-vetinari** [comment]
> so we see `644` on Linux/macOS and `666` on Windows in CI.

Permissions on windows don't follow the unix permission model anyway. You probably know this [article](https://fasterthanli.me/articles/i-want-off-mr-golangs-wild-ride), and it talks about much, _much_ more than that, but I would just reflect this in the windows tests - or perhaps even better - just test for the main executable bit.

**Review by FFY00 — APPROVED** [review]
Thanks!

I have added a test for the built wheel and skipped the executable bit tests on Windows.

**Comment by rgommers** [comment]
thanks!

**Pull request merged**
