### PR TITLE
Project.platform_tag: Handle the case of 32bit Python on x86_64

### LINKED ISSUE #123: platform_tag is wrong in 32-bit builds on 64-bit Linux kernels
meson-python 0.8.0 creates a wheel named `scipy-1.9.0rc3-cp310-cp310-linux_x86_64.whl` when run on an i386 Docker image, for example on `ubuntu-bionic-i386` (see https://github.com/mkoeppe/sage/runs/7599750782).

Ref: https://trac.sagemath.org/ticket/34081#comment:47

### PR DESCRIPTION
**Pull request by mkoeppe**
Fixes #123

### CODE REVIEW

**Comment by mkoeppe** [comment]
I've tested this successfully within Sage - https://trac.sagemath.org/ticket/34081#comment:53

**Review by rgommers — APPROVED** [review]
Thanks @mkoeppe. The fix looks good to me. The one question I have is whether we can expect a similar issue with 32-bit Python on any other platforms - Windows or non-x86 Linux for example. This is worth checking the code for at the same time.

**Comment by mkoeppe** [comment]
I only know about this case of x86 on x86_64 on Linux, sorry

**Review by FFY00 — APPROVED** [review]
Thanks! I changed the maxsize check to a hex literal.

**Pull request merged**
