### PR TITLE
BUG: fix mapping tags

### LINKED ISSUE #95: Python/ABI tag wrong on all platforms
The platform tag for my module is set to '-py-none-' on all platforms despite creating a shared module.
Apart from the tag issue the installation goes well and the share module is included in the package
This only happens if no other shared or platlib libraries are included

I can trace the issue as follows (on linux):
in __init__.py
self._install_plan.get('targets', {}) does read the full installation path rather than {moduledir_shared} as destination of my shared module
This is weird for me, because when I run pip wheel --cache-dir 'pybuilddir' and manually read the "intro-install_plan.json" file in the pybuilddir, I see {moduledir_shared} in front of the shared module

The problem then happens in function _files_by_tag (_init__.py line 727): 
```
if (
    not mesonpy._compat.is_relative_to(destination, '{py_platlib}')
    and not mesonpy._compat.is_relative_to(destination, '{moduledir_shared}')
):
    continue
tag = self._calculate_file_abi_tag_heuristic(file)
```
Because the destination is not relative to '{moduledir_shared}' it never reaches the point _calculate_file_abi_tag_heuristic(file) for the module file. 
Because of this:
- the function  _select_abi_tag [line 737] receives no tags 
- and thus the functions python_tag [line 647] and abi_tag [line 654] return 'py' and 'none'

Any idea why my shared module destination is not detected as {moduledir_shared}?

### PR DESCRIPTION
**Pull request by FFY00**
Fixes #95

### CODE REVIEW

**Comment by FFY00** [comment]
@rgommers @peter-urban can you check if things now work properly for you?

**Comment by peter-urban** [comment]
@FFY00 This fix resolves the issue for my project
Thanks a lot!

**Comment by FFY00** [comment]
Cool, will just wait for @rgommers to ack and I'll merge and then make a bugfix release.

**Comment by rgommers** [comment]
Thanks @FFY00 and @peter-urban. If it solves things for you then I'd say go ahead and merge. I cannot test this, because I can reproduce the problem _only_ when using build isolation (which makes it impossible to use a dev version). I'll comment on the issue.

**Comment by FFY00** [comment]
Since #111 also got merged, I am gonna do a normal release, not bugfix.

**Comment by rgommers** [comment]
SGTM, thanks. Please ping me for re-testing once that is done.

**Comment by FFY00** [comment]
I have released 0.8.0, which hopefully fixes all issues you were having :pray:

**Comment by rgommers** [comment]
Yes, that fixed it, thanks 😄 🚀

**Comment by peter-urban** [comment]
I also want to confirm that 0.8.0 fixes the issue for me. Thanks :-)

**Pull request merged**
