### PR TITLE
.github/workflows/ci-sage.yml: Make sure git is available

### PR DESCRIPTION
**Pull request by mkoeppe**
... in the build containers

### CODE REVIEW

**Review by FFY00 — APPROVED** [review]

**Comment by FFY00** [comment]
Looks like our tests are failing.

**Comment by mkoeppe** [comment]
Yes, see https://github.com/FFY00/meson-python/issues/150#issuecomment-1261410641

**Comment by mkoeppe** [comment]
Let me know if I should change anything in the `pytest` options so that you can see enough detail.

**Comment by FFY00** [comment]
I suspect the fails are due to an old `pyproject-metadata` dependency.

**Comment by mkoeppe** [comment]
Updated in https://git.sagemath.org/sage.git/commit/?id=004197d2eb3fec2104e25053b2b90045c61e95d3 to 0.6.1

**Comment by FFY00** [comment]
Just pushed a fix for the `pyproject-metadata` version mismatch, hopefully everything will pass now.

**Comment by FFY00** [comment]
The archlinux test passed, so I think we are good :tada:

**Comment by mkoeppe** [comment]
Failures on `centos-stream-8`, `gentoo-python3.9`

**Comment by FFY00** [comment]
Alright, those fails are different. The gentoo one seems like it might be a genuine issue, and the centos one is due to some weirdness in the tests. I am gonna mark them as not required and try to tackle them in followup PRs.

**Comment by rgommers** [comment]
Gentoo will be the same issue as we had before for building SciPy, that is gh-127.

**Pull request merged**
